# Generated by Django 5.2.7 on 2025-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado'), ('PAGO', 'Pago (Contas a Pagar)'), ('RECEBIDO', 'Recebido (Contas a Receber)')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
    ]
